setono_sylius_facebook_admin_pixel:
    resource: |
        section: admin
        alias: setono_sylius_facebook.pixel
        templates: "@SyliusAdmin\\Crud"
        redirect: index
        grid: setono_sylius_facebook_admin_pixel
        vars:
            all:
                subheader: setono_sylius_facebook.ui.manage_pixels
                templates:
                    form: "@SetonoSyliusFacebookPlugin/Admin/Pixel/_form.html.twig"
            index:
                icon: 'facebook'
    type: sylius.resource

setono_sylius_facebook_admin_pixel_reset_failed_events:
    path: /{id}/events/failed/reset
    methods: [PATCH]
    defaults:
        _controller: setono_sylius_facebook.controller.action.pixel.reset_failed_events
        _sylius:
            section: admin
            permission: true
            redirect:
                route: setono_sylius_facebook_admin_pixel_index
